baseURL = 'https://netlagina.github.io/best-port-to-play/'
languageCode = 'en-us'
title = 'Best Port To Play'
theme = 'hugo-book'
[params]
  BookTheme = 'auto'
  BookSection = 'docs'
  BookComments = false
